<%@ Page Title="" Language="VB" MasterPageFile="~/master_main.Master" AutoEventWireup="false" CodeFile="frm_admin_page.aspx.vb" Inherits="admin_frm_admin_page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:Panel ID="Panel1" runat="server">
    <center>
        <asp:Table ID="Table1" runat="server" Height="356px" Width="853px" 
            Font-Bold="True" Font-Size="Medium">
                 
            <asp:TableRow runat="server">
                <asp:TableCell runat="server">Course Name</asp:TableCell>
                   
                <asp:TableCell ID="TableCell1" runat="server">
                    <asp:TextBox ID="txtcname" runat="server"></asp:TextBox></asp:TableCell>
                     <asp:TableCell ID="TableCell9" runat="server">
                         <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="Please Enter Course Name" ControlToValidate="txtcname" ForeColor="#FF3300"></asp:RequiredFieldValidator></asp:TableCell>
            </asp:TableRow>

             <asp:TableRow ID="TableRow1" runat="server">
                <asp:TableCell ID="TableCell2" runat="server">Course Description</asp:TableCell>
                <asp:TableCell ID="TableCell3" runat="server">
                    <asp:TextBox ID="txtdesc" runat="server"></asp:TextBox></asp:TableCell>
                    <asp:TableCell ID="TableCell10" runat="server">
                         <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="Please Enter Course Description" ControlToValidate="txtdesc" ForeColor="#FF3300"></asp:RequiredFieldValidator></asp:TableCell>
            </asp:TableRow>

             <asp:TableRow ID="TableRow2" runat="server">
                <asp:TableCell ID="TableCell4" runat="server">Course Price</asp:TableCell>
                <asp:TableCell ID="TableCell5" runat="server">
                    <asp:TextBox ID="txtcp" runat="server"></asp:TextBox></asp:TableCell>
                    <asp:TableCell ID="TableCell11" runat="server">
                         <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="Please Enter Course Price" ControlToValidate="txtcp" ForeColor="#FF3300"></asp:RequiredFieldValidator></asp:TableCell>
            </asp:TableRow>

             <asp:TableRow ID="TableRow3" runat="server">
                <asp:TableCell ID="TableCell6" runat="server">Course Image</asp:TableCell>
                <asp:TableCell ID="TableCell7" runat="server">
                    <asp:FileUpload ID="FileUpload1" runat="server" /></asp:TableCell>
                    <asp:TableCell ID="TableCell12" runat="server">
                         <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ErrorMessage="Please Enter Course Image" ControlToValidate="FileUpload1" ForeColor="#FF3300"></asp:RequiredFieldValidator></asp:TableCell>
            </asp:TableRow>
                 

            <asp:TableRow ID="TableRow4" runat="server">
                <asp:TableCell ID="TableCell8" runat="server">
                    <asp:Button ID="btnsave" runat="server" Text="Save Data" BackColor="#3399FF" ForeColor="White" Height="50px" 
              Width="150px" /></asp:TableCell>
           
               
            </asp:TableRow>
        </asp:Table>
        <br />
        <br />
        <asp:Label ID="lblcourse" runat="server" Text="Label"></asp:Label>
        </center>
    </asp:Panel>
    <center>
        <asp:GridView ID="coursegv" runat="server" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" BackColor="#DEBA84" 
            BorderColor="#DEBA84" BorderWidth="1px" CellPadding="3" DataKeyNames="cid,cname,cdesc,cprice,cimg" 
            Height="306px" Width="1005px" BorderStyle="None" CellSpacing="2" 
            AutoGenerateColumns="False">
            <Columns>
                <asp:BoundField DataField="cid" HeaderText="Cid" />
                <asp:BoundField DataField="cname" HeaderText="Course Name" />
                <asp:BoundField DataField="cdesc" HeaderText="Course Description" />
                <asp:BoundField DataField="cprice" HeaderText="Course Price" />
                <asp:ImageField DataImageUrlField="cimg" HeaderText="Course Images">
                    <ControlStyle Height="150px" Width="150px" />
                </asp:ImageField>
            </Columns>
            <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
            <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
            <PagerStyle ForeColor="#8C4510" 
                HorizontalAlign="Center" />
            <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
            <SelectedRowStyle BackColor="#738A9C" ForeColor="White" Font-Bold="True" />
            <SortedAscendingCellStyle BackColor="#FFF1D4" />
            <SortedAscendingHeaderStyle BackColor="#B95C30" />
            <SortedDescendingCellStyle BackColor="#F1E5CE" />
            <SortedDescendingHeaderStyle BackColor="#93451F" />
        </asp:GridView>
    </center>
</asp:Content>

