<%@ Page Title="" Language="VB" MasterPageFile="~/master_main.Master" AutoEventWireup="false" CodeFile="frm_class.aspx.vb" Inherits="User_frm_class" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <asp:Panel ID="Panel1" runat="server">
    <center>
        <asp:Label ID="lblclass" runat="server" 
            Text="Buy Your Faviorate Course and Get High Exprecence" BackColor="#FFFF66" 
            Font-Bold="True" Font-Size="XX-Large" ForeColor="Red"></asp:Label>
        <br />
        <br />
        <asp:Label ID="lblname" runat="server" Text="Welcome: "></asp:Label>
        <br />
        <br />
       <%-- <asp:GridView ID="classgv" runat="server" AllowSorting="True" 
            DataKeyNames="cid" Height="384px" Width="1005px" CellPadding="4" 
            ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" />
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>--%>
           <asp:GridView ID="coursegv" runat="server" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" BackColor="#DEBA84" 
            BorderColor="#DEBA84" BorderWidth="1px" CellPadding="3" DataKeyNames="cid,cname,cdesc,cprice,cimg" 
            Height="306px" Width="1005px" BorderStyle="None" CellSpacing="2" 
            AutoGenerateColumns="False">
            <Columns>
                <asp:BoundField DataField="cid" HeaderText="Cid" />
                <asp:BoundField DataField="cname" HeaderText="Course Name" />
                <asp:BoundField DataField="cdesc" HeaderText="Course Description" />
                <asp:BoundField DataField="cprice" HeaderText="Course Price" />
                <asp:ImageField DataImageUrlField="cimg" HeaderText="Course Images">
                    <ControlStyle Height="150px" Width="150px" />
                </asp:ImageField>
            </Columns>
            <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
            <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
            <PagerStyle ForeColor="#8C4510" 
                HorizontalAlign="Center" />
            <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
            <SelectedRowStyle BackColor="#738A9C" ForeColor="White" Font-Bold="True" />
            <SortedAscendingCellStyle BackColor="#FFF1D4" />
            <SortedAscendingHeaderStyle BackColor="#B95C30" />
            <SortedDescendingCellStyle BackColor="#F1E5CE" />
            <SortedDescendingHeaderStyle BackColor="#93451F" />
        </asp:GridView>
    </center>
    </asp:Panel>
</asp:Content>


